### ISSUE TITLE
Check for `undefined`

### ISSUE THREAD

**Issue by charlesponti** [noxsnono/shop_front_vuex#1]
https://github.com/noxsnono/shop_front_vuex/blob/9fa68e602e2f1589104d937c98dafcf35536ed20/src/store.js#L27

This line throws an error because the above line only check if `state.basket` is `null` but not `undefined`.

**Comment by noxs-jj** [comment]
Fixed @charlesponti 

https://github.com/noxsnono/shop_front_vuex/commit/3a174b22cce742675364e99d482ed8fe634a9e6e
